In [19]:
import torch
torch.manual_seed(0)
tensor1 = torch.rand(7,7)
tensor1

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [20]:
torch.manual_seed(0)
tensor2 = torch.rand(1,7)
mul = torch.matmul(tensor1,tensor2.T) # T to transpose and make it 7,1
mul 

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [21]:
# torch.cuda.seed()  is used in PyTorch to set the random seed for CUDA operations, which allows for reproducible results when using CUDA (GPU) computations. 

In [23]:
torch.manual_seed(1234)
ten1 = torch.rand(2,3,device='mps')
torch.manual_seed(1234)
ten2 = torch.rand(2,3, device='mps')

In [26]:
ten_mul = torch.matmul(ten1,ten2.T)
ten_mul

tensor([[0.5887, 0.8212],
        [0.4837, 0.6981]], device='mps:0')

In [30]:
ten_mul.max(), ten_mul.min()

(tensor(0.8212, device='mps:0'), tensor(0.4837, device='mps:0'))

In [31]:
ten_mul.argmax(), ten_mul.argmin()

(tensor(1, device='mps:0'), tensor(2, device='mps:0'))

In [39]:
torch.manual_seed(7)
tens1 = torch.rand(1, 1, 1, 10)
tens1, tens1.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [38]:
tens2 = tens1.squeeze()
tens2, tens2.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))