In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
print(torch.__version__)

1.13.1


## Intro to Tensors
### Creating tensors


In [4]:
scalar = torch.tensor(2) # torch.tensor() is used to create a tensor
print(scalar) # print the tensor
print(scalar.item()) # item() is used to get the value of the tensor
print(scalar.ndim) # ndim is used to check the dimension of the tensor, like row or column

tensor(2)
2
0


In [8]:
vector = torch.tensor([1,2,3,4,5])
print(vector)
print(vector.ndim) # can say no of square brackets (levels of hierarchy)
print(vector.shape) # shape is used to check the shape of the tensor i.e. no of items inside square brackets

tensor([1, 2, 3, 4, 5])
1
torch.Size([5])


In [7]:
MATRIX = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [9]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape) # 2,3,3 means 2 matrices of 3 rows and 3 columns (3x3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([2, 3, 3])


by convention tensors and matrices are represented by capital letters and scalar and vectors by lower case letters

### Random Tensors

In [5]:
#creating a random tensor
random_tensor = torch.rand(3,4) # 3 rows and 4 columns
random_tensor

tensor([[0.3303, 0.0156, 0.3757, 0.7011],
        [0.8701, 0.0452, 0.9146, 0.2333],
        [0.1509, 0.6396, 0.4679, 0.4092]])

In [7]:
#random image tensor
random_image_tensor = torch.rand(3,224,244) # height, width, color channel (RGB)
random_image_tensor.ndim

3

In [10]:
#zeros and ones tensor
zeros_tensor = torch.zeros(3,4)
#zeros_tensor = torch.zeros(size=(3,4)) # same way for size
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])