In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
print(torch.__version__)

1.13.1


## Intro to Tensors
### Creating tensors


In [4]:
scalar = torch.tensor(2) # torch.tensor() is used to create a tensor
print(scalar) # print the tensor
print(scalar.item()) # item() is used to get the value of the tensor
print(scalar.ndim) # ndim is used to check the dimension of the tensor, like row or column

tensor(2)
2
0


In [8]:
vector = torch.tensor([1,2,3,4,5])
print(vector)
print(vector.ndim) # can say no of square brackets (levels of hierarchy)
print(vector.shape) # shape is used to check the shape of the tensor i.e. no of items inside square brackets

tensor([1, 2, 3, 4, 5])
1
torch.Size([5])


In [7]:
MATRIX = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
torch.Size([3, 3])


In [9]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape) # 2,3,3 means 2 matrices of 3 rows and 3 columns (3x3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([2, 3, 3])


by convention tensors and matrices are represented by capital letters and scalar and vectors by lower case letters

### Random Tensors

In [5]:
#creating a random tensor
random_tensor = torch.rand(3,4) # 3 rows and 4 columns
random_tensor

tensor([[0.3303, 0.0156, 0.3757, 0.7011],
        [0.8701, 0.0452, 0.9146, 0.2333],
        [0.1509, 0.6396, 0.4679, 0.4092]])

In [7]:
#random image tensor
random_image_tensor = torch.rand(3,224,244) # height, width, color channel (RGB)
random_image_tensor.ndim

3

In [24]:
#zeros and ones tensor
zeros_tensor = torch.zeros(3,4)
#zeros_tensor = torch.zeros(size=(3,4)) # same way for size
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
ones_tensor.dtype # data type of the tensor

torch.float32

In [19]:
one_to_ten = torch.arange(0,10)
torch.arange(start=0,end=10,step=2) 

tensor([0, 2, 4, 6, 8])

In [22]:
# tensors like
# to create a tensor with same shape as other tensor
ones_tensor_like = torch.zeros_like(ones_tensor)
ones_tensor_like

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
#default tensor type is float32

float_16_tensor = torch.tensor([1,2,3],
                                                dtype=torch.float16, # data type of the tensor
                                                device='mps', # what device to use, mps for mac metal gpu, by default cpu
                                                requires_grad = False # to calculate gradient or not
)
float_16_tensor

tensor([1., 2., 3.], device='mps:0', dtype=torch.float16)

In [13]:
float_32_tensor= float_16_tensor.type(torch.float32)
float_32_tensor

tensor([1., 2., 3.], device='mps:0')

In [17]:
float_32_tensor * float_16_tensor # possible, results in float32 tensor, this is type casting, float * int = float is also possible

tensor([1., 4., 9.], device='mps:0')

In [21]:
print(float_16_tensor.dtype)
print(float_16_tensor.device)
print(float_16_tensor.requires_grad)
print(float_16_tensor.shape)

torch.float16
mps:0
False
torch.Size([3])


### Operations on tensors
- Addition
- Subtraction
- Division
- Element wise multiplication
- Matrix Multiplication (also known as dot product)

In [22]:
operations = torch.tensor([1,2,3])
operations +10 # add 10 to each element

tensor([11, 12, 13])

In [26]:
operations * 10 # multiply 10 to each element (element wise multiplication)

tensor([10, 20, 30])

In [24]:
torch.mul(operations,10) # same as above

tensor([10, 20, 30])

In [25]:
operations / 10 # divide 10 to each element

tensor([0.1000, 0.2000, 0.3000])

In [27]:
tensor_mul_1 = torch.tensor([1,2,3])
tensor_mul_2 = torch.tensor([4,5,6])
print(f"element wise multiplication: {tensor_mul_1 * tensor_mul_2}")

element wise multiplication: tensor([ 4, 10, 18])


In [29]:
tensor_mul_1 @ tensor_mul_2 # same as above

tensor(32)

In [31]:
torch.matmul(tensor_mul_1,tensor_mul_2) # same as above

tensor(32)

## some benchmarking

In [7]:
%%time
value =0
tensor1 = torch.rand(100000)

for i in range(len(tensor1)):
    value += tensor1[i] * tensor1[i]

print(tensor1,tensor1.shape,tensor1.ndim)
print(value)

tensor([0.1594, 0.9236, 0.7792,  ..., 0.9400, 0.6585, 0.0726]) torch.Size([100000]) 1
tensor(33256.2500)
CPU times: user 236 ms, sys: 2.27 ms, total: 238 ms
Wall time: 237 ms


In [8]:
%%time 
torch.matmul(tensor1,tensor1)

CPU times: user 552 µs, sys: 884 µs, total: 1.44 ms
Wall time: 3.03 ms


tensor(33256.6836)

In [10]:
%%time 
tensor1.dot(tensor1) # faster than above
# dot and matmul gives same result for 1D tensor 

CPU times: user 118 µs, sys: 30 µs, total: 148 µs
Wall time: 130 µs


tensor(33256.6836)

In [11]:
tensor2 = torch.rand(100,100,100)
tensor2.shape,tensor2.ndim


(torch.Size([100, 100, 100]), 3)

In [13]:
# print(tensor2.dot(tensor2)) # gives error, dot product is not possible for 3D tensor
tensor2.matmul(tensor2) # matrix multiplication is possible for 3D tensor

tensor([[[25.6859, 22.5577, 24.5622,  ..., 23.8194, 26.1013, 29.0120],
         [23.6808, 19.7852, 23.4228,  ..., 21.9910, 23.5933, 25.4758],
         [27.0453, 24.8169, 26.9902,  ..., 27.2657, 27.5382, 30.4926],
         ...,
         [24.2716, 21.5646, 26.4907,  ..., 23.3432, 24.1977, 24.3833],
         [24.7912, 22.6355, 26.1069,  ..., 25.5642, 26.7590, 27.0885],
         [24.5461, 22.6192, 25.4534,  ..., 24.9676, 26.7283, 27.5899]],

        [[26.5610, 25.4498, 24.0886,  ..., 22.3584, 22.4774, 25.3629],
         [24.6214, 23.4366, 21.8434,  ..., 20.1613, 23.2423, 23.6459],
         [24.9198, 23.7422, 22.8828,  ..., 21.7242, 21.3881, 21.8676],
         ...,
         [26.4948, 25.5872, 25.4883,  ..., 21.3440, 24.1105, 24.7633],
         [27.7279, 26.1621, 25.0435,  ..., 23.8808, 25.4300, 27.8664],
         [26.6840, 26.3687, 24.2728,  ..., 23.6758, 24.3738, 25.9267]],

        [[23.2790, 22.7735, 21.7494,  ..., 22.5036, 23.7909, 20.2634],
         [27.3749, 26.8387, 25.5875,  ..., 24

In [15]:
tensor3 = torch.rand(100,100)
# tensor3.dot(tensor3) # dot product is possible for 2D tensor

In [22]:
# can also use torch.mm(tensor3,tensor3) for matrix multiplication of 2D tensor
# torch.mm does not broadcast, matmul does broadcast, meaning matmul can multiply between tensors of different shapes by adjusting the shape of the smaller tensor
print(torch.mm(tensor3,tensor3))
# print(tensor2.mm(tensor2)) # gives error, mm is not possible for 3D tensor

tensor([[25.5972, 27.0957, 26.6306,  ..., 24.8638, 27.8095, 23.9729],
        [25.5634, 29.4885, 26.5628,  ..., 24.2803, 24.8205, 25.0753],
        [21.1980, 24.3084, 20.9092,  ..., 21.5096, 22.2073, 20.7957],
        ...,
        [26.3247, 29.4175, 25.9391,  ..., 23.7574, 26.9102, 25.2673],
        [25.3953, 29.8177, 25.8474,  ..., 23.5167, 25.9400, 24.4299],
        [24.1506, 26.5884, 24.8052,  ..., 22.0899, 23.3106, 23.7027]])


## Rules for matrix multiplication
- The inner dimensions must match <br>
(3,2) @ (2,3) will work because the inner dimensions(2,2) match <br>
(3,2) @ (3,2) will not work because the inner dimensions(2,3) do not match

(rows,column)

- The resulting matrix has the shape of the outer dimensions <br>
(3,2) @ (2,3) will result in a (3,3) matrix

In [32]:
tensorA = torch.tensor([[1,2],[3,4],[5,6]]) # 3x2
tensorB = torch.tensor([[2,4],[6,8],[10,12]]) # 3x2
# print(tensorA @ tensorB) # error as inner dimensions are not same
# to fix this we can transpose tensorB, i.e. convert 3x2 to 2x3

print(tensorB.shape)
tensorB = tensorB.T # transpose
print(tensorB.shape)
print(tensorA @ tensorB) # now it works

torch.Size([3, 2])
torch.Size([2, 3])
tensor([[ 10,  22,  34],
        [ 22,  50,  78],
        [ 34,  78, 122]])


## Tensor aggregation
- finding mean, sum, max, min, standard deviation, variance, product, argmax, argmin, etc

In [45]:
tensor_agg = torch.arange(0,100,10)
print(tensor_agg)
print(tensor_agg.sum()) # sum of all elements
print(tensor_agg.prod()) # product of all element
print(tensor_agg.max()) # max of all elements
print(tensor_agg.min()) # min of all elements
# can also use torch.sum(tensor_agg), torch.prod(tensor_agg), torch.max(tensor_agg), torch.min(tensor_agg), etc

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(450)
tensor(0)
tensor(90)
tensor(0)


In [43]:
# print(tensor_agg.dtype) # int64 (long)
#mean and std are not possible for int64, so we need to convert it to float
tensor_agg = tensor_agg.type(torch.float32)
print(tensor_agg.mean()) # mean of all elements, can also use tensor_agg.sum()/len(tensor_agg)
print(tensor_agg.var()) # variance of all elements, can also use tensor_agg.std()**2
print(tensor_agg.std()) # standard deviation of all elements, can also use tensor_agg.var().sqrt()

tensor(45.)
tensor(916.6667)
tensor(30.2765)


In [44]:
print(tensor_agg.argmax()) # index of max element
print(tensor_agg.argmin()) # index of min element

tensor(9)
tensor(0)


In [4]:
torch.tensor([1,2,3,4,5,6,7,8,9,10]).reshape(2,5) # reshape to 2x5, breaks the tensor into 2x5

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [6]:
torch.tensor([1,2,3,4,5,6,7,8,9,10]).reshape(2,-1) 
# reshape to 2x5, breaks the tensor into 2x5, -1 means automatically adjust the number of columns

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])